export const GAME_CONFIG = {
  world: {
    width: 540,
    height: 720,
    groundY: 652,
    birdX: 160,
    birdStartY: 337,
  },
  physics: {
    gravity: 1450,
    initialVelocity: -410,
    flapVelocity: -425,
    shieldBounceVelocity: -300,
    maxFallVelocity: 660,
    basePipeSpeed: 185,
    speedPerGate: 4,
    maxPipeSpeed: 255,
    slowFlightSpeedMultiplier: 0.7,
    maxFrameDelta: 0.035,
    topBoundary: 11,
    groundCollisionPadding: 14,
    birdLeftRadius: 16,
    birdRightRadius: 17,
    birdVerticalRadius: 12,
  },
  pipes: {
    width: 76,
    gapHeight: 184,
    spacing: 270,
    initialCount: 2,
    respawnEdgeOffset: 1,
    spawnTopMin: 112,
    spawnTopRange: 276,
    motionStartsAfter: 3,
    motionEvery: 4,
    motionAmplitude: 18,
    motionRate: 1.5,
    horizontalCollisionPadding: 1,
  },
  pickups: {
    coinOffsets: [112, 144, 176],
    powerUpOffset: 218,
    coinVerticalSpacing: 23,
    powerUpVerticalOffset: 38,
    gemEvery: 7,
    starEvery: 11,
    starCoinValue: 10,
    powerUpStartPipe: 2,
    powerUpEvery: 5,
    utilityPowerUpEvery: 3,
    coinCollisionRadius: 23,
    magnetCollectionRadius: 94,
    powerUpCollisionRadius: 27,
    coinDespawnRadius: 13,
    powerUpDespawnRadius: 17,
    magnetAttractionRadius: 150,
    magnetPullRate: 4.5,
  },
  powerUps: {
    shield: { invulnerabilityDuration: 1.8 },
    magnet: { duration: 8, maxDuration: 14 },
    double: { duration: 8, maxDuration: 16 },
    slow: { duration: 5, maxDuration: 10 },
  },
  scoring: {
    gemCoinValue: 5,
    streakLength: 5,
    streakBonusCoins: 3,
  },
  countdown: {
    seconds: 3,
    goDuration: 0.45,
  },
  rendering: {
    maxParticles: 72,
    maxDevicePixelRatio: 1.5,
    maxFramesPerSecond: 60,
    idleFramesPerSecond: 30,
  },
  audio: {
    masterVolume: 0.72,
    musicIntervalMs: 390,
    melody: [523.25, 659.25, 783.99, 659.25, 587.33, 698.46, 880, 698.46],
  },
  storage: {
    bestScore: 'air-jumper-best',
    legacyBestScore: 'skyward-best',
    soundPreference: 'air-jumper-sound',
    legacySoundPreference: 'skyward-sound',
    profile: 'air-jumper-profile',
  },
} as const;

export type GameConfig = typeof GAME_CONFIG;
